Update withtesting.yml
removed errors

diff --git a/.github/workflows/withtesting.yml b/.github/workflows/withtesting.yml
--- a/.github/workflows/withtesting.yml
+++ b/.github/workflows/withtesting.yml
@@ -59,37 +59,37 @@ jobs:
           docker.io/pawandevops/cockpit-docker-images:latest
           docker.io/pawandevops/cockpit-docker-images:${{ env.VERSION }}
 
-    test-docker-image:
-    runs-on: ubuntu-latest
-    needs: [ build ]
+  test-docker-image:
+      runs-on: ubuntu-latest
+      needs: [ build ]
 
-    steps:
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+      steps:
+        - name: Set up Docker Buildx
+          uses: docker/setup-buildx-action@v1
 
-    - name: Load the Docker image from build stage
-      run: docker load -i /tmp/image.tar
-      working-directory: ${{ github.workspace }}
+        - name: Load the Docker image from build stage
+          run: docker load -i /tmp/image.tar
+          working-directory: ${{ github.workspace }}
 
-    - name: Run the Docker container
-      run: docker run -d -p 8080:8080 --name go-webapp-sample pawandevops/cockpit-docker-images:${{ env.VERSION }}
+        - name: Run the Docker container
+          run: docker run -d -p 8080:8080 --name go-webapp-sample pawandevops/cockpit-docker-images:${{ env.VERSION }}
 
-    - name: Test the health endpoint
-      run: |
-        sleep 10 # Wait for the container to be fully up and running
-        curl -f http://localhost:8080/api/health || (docker logs go-webapp-sample && exit 1)
-      continue-on-error: true
+        - name: Test the health endpoint
+          run: |
+            sleep 10 # Wait for the container to be fully up and running
+            curl -f http://localhost:8080/api/health || (docker logs go-webapp-sample && exit 1)
+          continue-on-error: true
 
-    - name: Check test result
-      run: |
-        if [ $? -eq 0 ]; then
-          echo "Tests passed successfully"
-        else
-          echo "Tests failed"
-          exit 1
-        fi
+        - name: Check test result
+          run: |
+              if [ $? -eq 0 ]; then
+                echo "Tests passed successfully"
+              else
+                echo "Tests failed"
+                exit 1
+              fi
 
-    - name: Stop and remove the Docker container
-      run: |
-        docker stop go-webapp-sample
-        docker rm go-webapp-sample
+        - name: Stop and remove the Docker container
+          run: |
+            docker stop go-webapp-sample
+            docker rm go-webapp-sample
